name = input("Enter your name")
age = input("Enter your age")
city = input("Enter your city name")
dream = input("Enter your dream company")
college = input("Enter your college name")
print()
print("=======STUDENT PROFILE========")
print("Name:", name)
print("Age:", age)
print("City:", city)
print("Dream Company:", dream)
print("College:", college)
