print("Hello World")
print("Welcome to Mission 80+")
print("My name is Mudassir")
print(786)
print(25+75)
print("Age:",18)
print("Hello\n World")
print("Python\tAI")
print("Python", "AI" , "ML")
print("Python" ,"AI" ,"ML",sep ="-")
print( 1, 2, 3, sep = "*")
print("Hello", end = " ")
print("World")
print("I love Python")
print("Mission \n 80+")
print("Python","AI", "ML" , sep = "->" )
print("Name:", "Mudassir", "\n", "Age:", 18, "\n", "Goal:", "AI ENGINEER")