Name = str(input("Enter your name :"))
Age = int(input("Enter your age :"))
Dob = str(input("Enter your date of birth :"))
City = str(input("Enter your city :"))
College = str(input("Enter your college name :"))
perc_in_10th = float(input("Enter your percentage in 10th :"))
perc_in_12th = float(input("Enter your percentage in 12th :"))

print("***********Student Profile***********")
print("Name:", Name)
print("Age:", Age)
print("Date of Birth:", Dob)
print("City:", City)
print("College:", College)
print("Percentage in 10th:", perc_in_10th)
print("Percentage in 12th:", perc_in_12th)
print("*************************************")